# Generated by Django 4.1.13 on 2026-04-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='author',
                    name='bio',
                    field=models.TextField(blank=True),
                ),
                migrations.AddField(
                    model_name='author',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, null=True),
                ),
                migrations.AddField(
                    model_name='author',
                    name='email',
                    field=models.EmailField(max_length=254, unique=True),
                ),
                migrations.AddField(
                    model_name='author',
                    name='gender',
                    field=models.CharField(default='other', max_length=10),
                ),
                migrations.AddField(
                    model_name='author',
                    name='updated_at',
                    field=models.DateTimeField(auto_now=True, null=True),
                ),
            ],
        ),
    ]
