# Generated by Django 4.1.13 on 2026-04-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='no_of_page',
            new_name='no_of_pages',
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='defult.jpg', upload_to='books/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
